<?php $year=$financialStats['year']; require __DIR__.'/summary.php'; ?>
<section class="panel finance-entry"><div class="section-heading"><div><h2>Regjistro faturë</h2><p>Një faturë për biznes për vit fiskal. Kërkoni me emër ose numër regjistrimi.</p></div></div>
    <form method="get" class="finance-search"><input type="hidden" name="year" value="<?=$year?>"><label class="field">Kërko biznes të pafaturuar<input name="q" maxlength="120" value="<?=e($query)?>" placeholder="Emri ose NRB" required></label><button type="submit"><svg class="button-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.8" cy="10.8" r="6.8"/><path d="m16 16 5 5"/></svg>Kërko</button></form>
    <?php if($query!==[]):?><p class="result-caption"><?=count($businesses)?> rezultate për “<?=e($query)?>”</p><?php endif;?>
    <?php if($businesses!==[]):?><form method="post" action="<?=e(app_url('/admin/finance/save-invoice.php'))?>" class="finance-form"><input type="hidden" name="_csrf" value="<?=e($csrf->token())?>"><input type="hidden" name="fiscal_year" value="<?=$year?>"><label class="field">Biznesi<select name="business_id" required><?php foreach($businesses as $business):?><option value="<?=(int)$business['id']?>"><?=e($business['registration_number'].' · '.$business['legal_name'].' · '.($business['estimated_tariff']===null?'Pa tarifë':number_format((float)$business['estimated_tariff'],2).' €'))?></option><?php endforeach;?></select></label><label class="field">Nr. i faturës<input name="invoice_number" maxlength="80" required></label><label class="field">Shuma (€)<input name="amount" type="number" min="0.01" step="0.01" required value="<?=e($businesses[0]['estimated_tariff']??'')?>"></label><label class="field">Data e lëshimit<input name="issued_on" type="date" required value="<?=e($year=== (int)date('Y')?date('Y-m-d'):$year.'-12-31')?>"></label><label class="field">Afati i pagesës<input name="due_on" type="date"></label><label class="field">Shënim<input name="notes" maxlength="500"></label><button type="submit">Regjistro faturën</button></form><?php elseif($query!==[]):?><div class="empty">Nuk u gjet biznes aktiv i pafaturuar që përputhet.</div><?php endif;?>
</section>
<section class="panel finance-entry"><div class="section-heading"><div><h2>Regjistro pagesë</h2><p>Pagesat e pjesshme pranohen; shuma nuk mund të tejkalojë bilancin.</p></div></div>
    <?php if($payableInvoices!==[]):?><form method="post" action="<?=e(app_url('/admin/finance/save-payment.php'))?>" class="finance-form"><input type="hidden" name="_csrf" value="<?=e($csrf->token())?>"><input type="hidden" name="fiscal_year" value="<?=$year?>"><label class="field">Fatura<select name="invoice_id" required><?php foreach($payableInvoices as $invoice):?><option value="<?=(int)$invoice['id']?>">#<?=e($invoice['invoice_number'])?> · <?=e($invoice['registration_number'])?> · <?=e($invoice['legal_name'])?> · Mbeten <?=number_format((float)$invoice['outstanding'],2,'.',',')?> €</option><?php endforeach;?></select></label><label class="field">Shuma e paguar (€)<input name="amount" type="number" min="0.01" step="0.01" required></label><label class="field">Data e pagesës<input name="paid_on" type="date" required value="<?=e(date('Y-m-d'))?>"></label><label class="field">Referenca<input name="reference" maxlength="100"></label><label class="field">Shënim<input name="notes" maxlength="500"></label><button type="submit">Regjistro pagesën</button></form><?php else:?><div class="empty">Nuk ka fatura me bilanc të papaguar.</div><?php endif;?>
</section>
<section class="panel"><h2>Faturat · <?=$year?></h2><div class="table-wrap"><table><thead><tr><th>Nr. fature</th><th>Biznesi</th><th>Lëshuar</th><th>Shuma</th><th>Paguar</th><th>Mbeten</th></tr></thead><tbody><?php foreach($invoices as $invoice):?><tr><td data-label="Nr. fature"><?=e($invoice['invoice_number'])?></td><td data-label="Biznesi"><?=e($invoice['registration_number'].' · '.$invoice['legal_name'])?></td><td data-label="Lëshuar"><?=e($invoice['issued_on'])?></td><td data-label="Shuma"><?=number_format((float)$invoice['amount'],2,'.',',')?> €</td><td data-label="Paguar"><?=number_format((float)$invoice['paid_amount'],2,'.',',')?> €</td><td data-label="Mbeten"><?=number_format((float)$invoice['outstanding'],2,'.',',')?> €</td></tr><?php endforeach;?></tbody></table><?php if($invoices===[]):?><div class="empty">Nuk ka fatura për këtë vit.</div><?php endif;?></div></section>