SET XACT_ABORT ON;
GO
CREATE UNIQUE INDEX UX_ARBK_LIST_REGULATION_ID
    ON dbo.ARBK_LIST(REGULATION_ID);
GO
CREATE INDEX IX_ARBK_LIST_BUSINESS_PAGE
    ON dbo.ARBK_LIST(Emri,REGULATION_ID)
    INCLUDE(NRBIZ,Qyteti,NACE_CODE_REG,NACEPERSHKRIMI,NACE_CODE_TARIFF,nace_veprimtaria_tariff,Statusi,ATK_MBYLLUR,ARBKrowGUID);
GO
CREATE INDEX IX_ARBK_LIST_NACE_CODE_REG
    ON dbo.ARBK_LIST(NACE_CODE_REG)
    INCLUDE(REGULATION_ID,Emri,NRBIZ);
GO
CREATE INDEX IX_NACE_LIST_NACE_CODE
    ON dbo.NACE_LIST(NACE_CODE)
    INCLUDE(NACErowGUID,REGULATIONID,Sektori,Veprimtaria,Tarifa);
GO
