<?php
declare(strict_types=1);

return [
    'APP_ENV' => 'development',
    'APP_DEBUG' => 'false',
    'APP_URL' => 'http://localhost/arbk',
    'APP_TIMEZONE' => 'Europe/Warsaw',
    'APP_SESSION_NAME' => 'arbk_admin',
    'APP_KEY' => '',
    'GRAPH_TENANT_ID' => '',
    'GRAPH_CLIENT_ID' => '',
    'GRAPH_CLIENT_SECRET' => '',
    'GRAPH_SENDER_MAILBOX' => 'no-reply@kryeqyteti.net',
    'GRAPH_BASE_URL' => 'https://graph.microsoft.com/v1.0',
    'GRAPH_TIMEOUT_SECONDS' => '15',
    'PASSWORD_RESET_TTL_SECONDS' => '1800',
    'FORCE_HTTPS' => 'false',
    'TRUST_PROXY_HEADERS' => 'false',
    // Both workstations use their own local SQL2025 instance.
    'DB_HOST' => 'localhost\\sql2025',
    'DB_NAME' => 'ARBK',
    'DB_USER' => '',
    'DB_PASSWORD' => '',
    'DB_TRUSTED_CONNECTION' => 'true',
    'DB_ENCRYPT' => 'false',
    'DB_TRUST_SERVER_CERTIFICATE' => 'true',
    'PAGE_SIZE' => '25',
    'CSRF_TTL_SECONDS' => '7200',
    'LOGIN_RATE_WINDOW_SECONDS' => '900',
    'LOGIN_RATE_MAX_ATTEMPTS' => '5',
    'LOGIN_RATE_BLOCK_SECONDS' => '900',
    'BACKUP_MODE' => 'managed',
    'DB_BACKUP_PATH' => '',
    'IMPORT_MAX_BYTES' => '157286400',
    'INVOICE_DUE_DAYS' => '30',
    'ANNUAL_INVOICE_BATCH_SIZE' => '200',
    'MUNICIPALITY_NAME' => 'KOMUNA E PRISHTINËS',
    'MUNICIPALITY_ADDRESS' => '',
    'MUNICIPALITY_CONTACT' => '',
    'MUNICIPAL_BANK_ACCOUNT' => '',
    'INVOICE_LEGAL_TEXT' => 'Kjo faturë është lëshuar nga sistemi komunal për tarifën vjetore të ushtrimit të veprimtarisë. Pagesa realizohet duke përdorur UNIREF-in e paraqitur në faturë.',
];
