<section class="hero"><h1><?=e($business['Emri'])?></h1><p>NRB <?=e($business['NRBIZ'])?> · ID <?=e($business['REGULATION_ID'])?></p></section>
<section class="panel"><h2>Të dhënat e biznesit</h2><dl class="detail-grid"><?php foreach(['NRBIZ'=>'Numri i regjistrimit','Emri'=>'Emri ligjor','EMRI_TREGTAR'=>'Emri tregtar','Lloji'=>'Lloji','Qyteti'=>'Komuna','Statusi'=>'Statusi ARBK','Pasiv'=>'Pasiv','date_pasivizimit'=>'Data e pasivizimit','NACE_CODE_REG'=>'Kodi NACE i regjistruar','NACEPERSHKRIMI'=>'Përshkrimi NACE','SEKTORI'=>'Sektori','NR_PUNETOREVE'=>'Numri i punëtorëve','MADHESIA'=>'Madhësia','TOTAL_M'=>'Gjithsej meshkuj','TOTAL_F'=>'Gjithsej femra','Viti'=>'Viti','MUAJI'=>'Muaji','DATA_SHUARJES'=>'Data e shuarjes','NACE_CODE_TARIFF'=>'Kodi NACE tarifor','nace_veprimtaria_tariff'=>'Veprimtaria tarifore','pronare_grua'=>'Pronare grua','pronesia_grua'=>'Pronësia e gruas (%)','pronar_veteran'=>'Pronar veteran','perqindja_veteran'=>'Pronësia e veteranit (%)','tarifa_me_lirim'=>'Tarifa me lirim','normalized_atk_status'=>'Statusi ATK','deactivated_at'=>'Data e mbylljes ATK'] as $key=>$label):?><div><dt><?=e($label)?></dt><dd><?php if(in_array($key,['Pasiv','pronare_grua','pronar_veteran'],true)):?><?=array_key_exists($key,$business)&&$business[$key]!==null?((int)$business[$key]===1?'Po':'Jo'):'—'?><?php elseif($key==='tarifa_me_lirim'&&$business[$key]!==null):?><?=number_format((float)$business[$key],2)?> €<?php else:?><?=e($business[$key]??'—')?><?php endif;?></dd></div><?php endforeach;?></dl></section>
<?php if(in_array($user['role_code'],['ADMIN','OFFICIAL'],true)):?>
<section class="panel"><h2>Editimi manual</h2><form method="post" action="<?=e(app_url('/admin/businesses/update.php'))?>"><input type="hidden" name="_csrf" value="<?=e($csrf->token())?>"><input type="hidden" name="business_id" value="<?=(int)$business['REGULATION_ID']?>"><div class="filters">
<?php foreach(['NRBIZ'=>'Numri i regjistrimit','Emri'=>'Emri ligjor','EMRI_TREGTAR'=>'Emri tregtar','Lloji'=>'Lloji','NACE_CODE_REG'=>'Kodi NACE','NACEPERSHKRIMI'=>'Përshkrimi NACE','SEKTORI'=>'Sektori','MADHESIA'=>'Madhësia','Qyteti'=>'Komuna','Statusi'=>'Statusi','Viti'=>'Viti','MUAJI'=>'Muaji','ATK_DATEMBYLLJE'=>'Data ATK (tekst)','NACE_CODE_TARIFF'=>'Kodi NACE tarifor','nace_veprimtaria_tariff'=>'Veprimtaria tarifore'] as $field=>$label):?><label class="field"><?=e($label)?><input name="<?=e($field)?>" value="<?=e($business[$field]??'')?>"></label><?php endforeach;?>
<?php foreach(['NR_PUNETOREVE'=>'Numri i punëtorëve','TOTAL_M'=>'Gjithsej meshkuj','TOTAL_F'=>'Gjithsej femra'] as $field=>$label):?><label class="field"><?=e($label)?><input type="number" min="0" name="<?=e($field)?>" value="<?=e($business[$field]??'')?>"></label><?php endforeach;?>
<?php foreach(['date_pasivizimit'=>'Data e pasivizimit','DATA_SHUARJES'=>'Data e shuarjes'] as $field=>$label):?><label class="field"><?=e($label)?><input type="date" name="<?=e($field)?>" value="<?=e(isset($business[$field])?substr((string)$business[$field],0,10):'')?>"></label><?php endforeach;?>
<?php foreach(['Pasiv'=>'Pasiv','ATK_MBYLLUR'=>'ATK mbyllur','pronare_grua'=>'Pronare grua','pronar_veteran'=>'Pronar veteran'] as $field=>$label):?><label class="field"><?=e($label)?><select name="<?=e($field)?>"><option value="">—</option><option value="1" <?=isset($business[$field])&&(int)$business[$field]===1?'selected':''?>>Po</option><option value="0" <?=isset($business[$field])&&(int)$business[$field]===0?'selected':''?>>Jo</option></select></label><?php endforeach;?>
<?php foreach(['pronesia_grua'=>'Pronësia e gruas (%)','perqindja_veteran'=>'Pronësia e veteranit (%)','NACE_REG_TARIFF'=>'Tarifa NACE','tarifa_me_lirim'=>'Tarifa me lirim'] as $field=>$label):?><label class="field"><?=e($label)?><input type="number" min="0" <?=in_array($field,['pronesia_grua','perqindja_veteran'],true)?'max="100"':''?> step="0.01" name="<?=e($field)?>" value="<?=e($business[$field]??'')?>"></label><?php endforeach;?>
</div><div class="actions"><button type="submit">Ruaj ndryshimet</button></div></form><p><small>Ndryshimet regjistrohen në auditim. Ndryshimi i kodit NACE anulon klasifikimin tarifor ekzistues.</small></p></section>
<?php endif;?>
<section class="panel"><h2>Klasifikimi komunal</h2><?php if($business['nace_list_id']):?><p><strong><?=e($business['nace_category'])?></strong></p><p>Tarifa: <?=number_format((float)$business['tariff_snapshot'],2)?> € · Metoda: <span class="badge <?=e($business['assignment_method'])?>"><?=e($business['assignment_method'])?></span> · <?=e($business['assigned_at'])?></p><?php else:?><p>Nuk ka klasifikim aktiv.</p><?php endif;?>
<?php if(in_array($user['role_code'],['ADMIN','OFFICIAL'],true)):?><form method="post" action="<?=e(app_url('/admin/businesses/classify.php'))?>"><input type="hidden" name="_csrf" value="<?=e($csrf->token())?>"><input type="hidden" name="business_id" value="<?=(int)$business['REGULATION_ID']?>"><label class="field">Kategori e vlefshme për NACE <?=e($business['NACE_CODE_REG'])?><select name="mapping_key" required><option value="">Zgjidhni</option><?php foreach($categories as $category):?><option value="<?=e($category['mapping_key'])?>"><?=e($category['sector'].' — '.$category['activity'])?> (<?=number_format((float)$category['tariff'],2)?> €)</option><?php endforeach;?></select></label><div class="actions"><button name="action" value="save">Ruaj</button><button name="action" value="next">Ruaj dhe vazhdo</button><a class="button secondary" href="<?=e(app_url('/admin/businesses/classification.php'))?>">Kthehu</a></div></form><?php endif;?></section>
